import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./componenets/Footer";
import Navbar from "./componenets/Navbar";
import { Providers } from "./providers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 export default function RootLayout({ children,}: Readonly<{ children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body
       className={`${inter.variable} antialiased`}>
         <Providers>
          <Navbar/>
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}

